### ISSUE TITLE
Question: BlockSnapshot vs. State().toContainer().get(DataQuery.of("UnsafeMeta")

### ISSUE THREAD

**Issue by vorburger** [hsyyid/Inspector#6]
Hello, this is Question, not a bug report or improvement suggestion (although it may be):

FYI I've looked at your plugin to learn how to save Block state and restore it, and initially looked at using your https://github.com/hsyyid/Inspector/blob/ee6b2ca0ac431120e4e23e85a8103d78d0e0ad47/src/main/java/io/github/hsyyid/inspector/listeners/PlayerBreakBlockListener.java and https://github.com/hsyyid/Inspector/blob/1f9b4fcc173b9284c0c978cdc7249aaa25dedf51/src/main/java/io/github/hsyyid/inspector/cmdexecutors/RollbackExecutor.java#L87, but then found https://docs.spongepowered.org/master/en-GB/plugin/blocks/modifying.html and in my tests found that seems to work just fine, see what I'm doing with it for a slightly different purpose in https://github.com/vorburger/SwissKnightMinecraft/blob/633baf583981829c2ddd25a00c686fffa3191893/SpongePowered/MyFirstSpongePlugIn/src/main/java/ch/vorburger/minecraft/logo/UndoableTurtle.xtend, so I was just curious and interested in if I'm missing something - does BlockSnapshot not fully work / miss some metadata that you know of? Thank you!

**Comment by hsyyid** [comment]
BlockSnapshot contains all data you'll need, for how I saved things on Inspector, it didn't matter.

**Comment by vorburger** [comment]
OK... thanks a lot for your reply! I'm closing this issue then.
